on:
  # Used for manually triggering jobs
  workflow_dispatch:
  # Run daily
  schedule:
  - cron: "0 8 * * *"

jobs:
  video-file-generation-job:
    runs-on: ubuntu-latest
    name: Generate video files
    steps:
    - name: Check out repository
      uses: actions/checkout@v2
    - name: Generate YouTube Video Files
      id: generator
      uses: ./actions/generator
      with:
        youtube-api-key: ${{ secrets.YOUTUBE_API_KEY }}
        template-file: ./actions/generator/generate-files-dotnet/video.md.template
        channel-id: "UCJKLCjeujQj-d3JjsbVtkJw"
        output: "./web/content/videos"
        tag-file: ./tags.yaml
    # output generation results as separate task.
    - name: Generated Videos Results
      run: 'ls ./web/content/videos; echo "Total Videos generated: ${{ steps.generator.outputs.generated-videos-count }}"'
    # Open PR and submit modified pages
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: Update Video Files
        committer: GitHub <noreply@github.com>
        author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
        branch: automated-video-update-patches
        delete-branch: true
        title: '[Automated] Update Video Files'
        body: |
          Updates video files with the generate-files command
          
          Auto-generated by [create-pull-request][1]

          [1]: https://github.com/peter-evans/create-pull-request
        assignees: runewake2
        reviewers: runewake2
        draft: false
