on: [push]

jobs:
  video-file-generation-job:
    runs-on: ubuntu-latest
    name: Generate video files
    steps:
    - name: Generate Files
      id: hello
      uses: ./generator
      with:
        youtube-api-key: ${{ secrets.YOUTUBE_API_KEY }}
        template-file: ./tools/generate-files-dotnet/video.md.template
        channel-id: "UCJKLCjeujQj-d3JjsbVtkJw"
        output: "./test"
    # Use the output from the `hello` step
    - name: Get the output time
      run: echo "The time was ${{ steps.hello.outputs.generated-videos-count }}"