on: [push]

jobs:
  video-file-generation-job:
    runs-on: ubuntu-latest
    name: Generate video files
    steps:
    - name: Check out repository
      uses: actions/checkout@v2
    - name: Generate Files
      id: generator
      uses: ./actions/generator
      with:
        youtube-api-key: ${{ secrets.YOUTUBE_API_KEY }}
        template-file: ./actions/generator/generate-files-dotnet/video.md.template
        channel-id: "UCJKLCjeujQj-d3JjsbVtkJw"
        output: "./web/content/videos"
    # output generation results as separate task.
    # TODO: Remove later
    - name: Generated Videos Results
      run: 'ls ./web/content/videos; echo "Total Videos generated: ${{ steps.generator.outputs.generated-videos-count }}"'