on: [push]

jobs:
  video-file-generation-job:
    runs-on: ubuntu-latest
    name: Generate video files
    steps:
    - name: Generate Files
      id: generator
      uses: ./actions/
      with:
        youtube-api-key: ${{ secrets.YOUTUBE_API_KEY }}
        template-file: ./actions/generator/generate-files-dotnet/video.md.template
        channel-id: "UCJKLCjeujQj-d3JjsbVtkJw"
        output: "./test"
    # output generation results as separate task.
    # TODO: Remove later
    - name: Generated Videos Results
      run: echo "Total Videos generated: ${{ steps.hello.outputs.generated-videos-count }}"