on: [push]

jobs:
  video-file-generation-job:
    runs-on: ubuntu-latest
    name: Generate video files
    steps:
    - name: Check out repository
      uses: actions/checkout@v2
    - name: Checkout submodules
      uses: textbook/git-checkout-submodule-action@master
      with:
        remote: true
    - name: Generate YouTube Video Files
      id: generator
      uses: ./actions/generator
      with:
        youtube-api-key: ${{ secrets.YOUTUBE_API_KEY }}
        template-file: ./actions/generator/generate-files-dotnet/video.md.template
        channel-id: "UCJKLCjeujQj-d3JjsbVtkJw"
        output: "./web/content/videos"
    # output generation results as separate task.
    # TODO: Remove later
    - name: Generated Videos Results
      run: 'ls ./web/content/videos; echo "Total Videos generated: ${{ steps.generator.outputs.generated-videos-count }}"'
    # Complete generating website content
    - name: Install Hugo Package
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: '0.69.0'
        extended: true
    - name: Build Site
      run: hugo --minify --source ./web
    - name: Generated Video Files
      run: 'ls ./web/public/videos'
    - name: Login to Container Registry
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.DOCKER_REGISTRY_URL }}
        username: ${{ secrets.AZURE_SERVICE_APP_ID }}
        password: ${{ secrets.AZURE_SERVICE_PASSWORD }}
    - name: Build DotCom Image
      uses: docker/build-push-action@v1
      with:
        registry: ${{ secrets.DOCKER_REGISTRY_URL }}
        repository: worldofzero-dotcom
        dockerfile: ./web/Dockerfile
        path: ./web
        tag_with_ref: true
        tag_with_sha: true
        push: true
    # - name: Build And Push Image
    #   run: |
    #     docker build ./web -t worldofzero.azurecr.io/worldofzero-dotcom:${{ github.sha }}
    #     docker push worldofzero.azurecr.io/worldofzero-dotcom:${{ github.sha }}